# Generated by Django 5.2.8 on 2025-11-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgeory',
            new_name='Category',
        ),
    ]
